image: Visual Studio 2017

-
  branches:
    only:
      - master
  configuration: Release
  environment:
    versuffix: ''

- 
  branches:
    only:
      - develop
      - feature/appveyor
  configuration: Debug
  environment:
    versuffix: '-beta'
    

version: '1.1.{build}$(versuffix)'

before_build:
  - nuget restore  
  - ps: |
        $xmlPath = "$env:appveyor_build_folder\NickBuhro.Translit\NickBuhro.Translit.csproj"
        $xml = [xml](get-content $xmlPath)
        $propertyGroup = $xml.Project.PropertyGroup
        $propertyGroup.Version = $env:appveyor_build_version
        $xml.Save($xmlPath)
        
artifacts:
  - path: NickBuhro.Translit\bin\$(configuration)\*.nupkg
    name: Package
