#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.1.{build}-beta

branches:
  only:
    - feature/appveyor

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU
configuration: Release

build:
  project: NickBuhro.Translit.sln

before_build:
  - nuget restore  
  - ps: |
        $xmlPath = "$env:appveyor_build_folder\NickBuhro.Translit\NickBuhro.Translit.csproj"
        $xml = [xml](get-content $xmlPath)
        $propertyGroup = $xml.Project.PropertyGroup[0]
        $propertyGroup.Version = $env:appveyor_build_version
        $xml.Save($xmlPath)

#---------------------------------#
#       tests configuration       #
#---------------------------------#


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
        
artifacts:

  - path: NickBuhro.Translit\bin\$(configuration)
    name: NickBuhro.Translit-{version}
    type: zip

  - path: NickBuhro.Translit\bin\$(configuration)\*.nupkg
    name: Package

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
