#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.4.{build}

branches:
  only:
    - master    

environment:
  COVERALLS_REPO_TOKEN:
    secure: GZLA0EL0qjA//e/pc8VZ8cc6zOPMBImlJpXc33Fr4G2LgvtmqTEYn3lKMh5ZKE7N

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU
configuration:
  - Debug
  - Release

build:
  project: NickBuhro.Translit.sln
  verbosity: minimal

before_build:
  - nuget restore  
  - ps: |
        $xmlPath = "$env:appveyor_build_folder\NickBuhro.Translit\NickBuhro.Translit.csproj"
        $xml = [xml](get-content $xmlPath)
        $propertyGroup = $xml.Project.PropertyGroup[0]
        $propertyGroup.Version = $env:appveyor_build_version
        $xml.Save($xmlPath)

#---------------------------------#
#       tests configuration       #
#---------------------------------#

after_test:
  - if "%CONFIGURATION%"=="Debug" (coverage.bat)
  - if "%CONFIGURATION%"=="Debug" (appveyor PushArtifact summary.mht)

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
        
artifacts:

  - path: NickBuhro.Translit\bin\$(configuration)    
    type: zip

  - path: NickBuhro.Translit\bin\$(configuration)\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: vDxpqHHdBtz+P6Nau7V8tLYhtc+5tE6qfEoQI8Vrse11k0vWCrAKY1vUvMoLFURB
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true
    appveyor_repo_tag_name: publish
