image:
  - Visual Studio 2017

branches:
  only:
    - feature/appveyor

configuration: Debug

before_build:
  - nuget restore

artifacts:
  - path: NickBuhro.Translit\bin\$(configuration)\*.nupkg
    name: Package
